### ISSUE TITLE
Fails to collect passenger configuration

### ISSUE THREAD

**Issue by Ra-Kumar** [RedHatSatellite/satellite-support#23]
If we have file '/etc/httpd/conf.d/passenger.conf', which is there on all Satellite version as it provided by 'mod_passenger-4.0.18-24.el7sat.x86_64' rpm, script skip reading file '/etc/httpd/conf.modules.d/passenger_extra.conf' in which we have actual passenger configuration, hence script provide blank output for passenger configuration.

**Comment by sthirugn** [comment]
@Ra-Kumar which script are you referring to?

**Comment by Ra-Kumar** [comment]
@sthirugn I am referring to 'check-perf-tuning' script.

**Comment by waldirio** [comment]
Hello @Ra-Kumar thanks for the heads up.
@sthirugn code updated.

**Comment by sthirugn** [comment]
@Ra-Kumar did you get a chance to run after the fix?

**Comment by Ra-Kumar** [comment]
@sthirugn yes, it's working fine now. Checking both the files:
~~~~~~~
Configuration : /etc/httpd/conf.d/passenger.conf
Custom-hiera  : apache::mod::passenger::passenger_max_pool_size
                apache::mod::passenger::passenger_max_request_queue_size
Current values:

Configuration : /etc/httpd/conf.modules.d/passenger_extra.conf
Custom-hiera  : apache::mod::passenger::passenger_max_pool_size
                apache::mod::passenger::passenger_max_request_queue_size
Current values:
  PassengerMaxPoolSize 12
  PassengerMaxRequestQueueSize 250

~~~~~~~~~~~~~~~~

**Comment by sthirugn** [comment]
Thanks, closing the issue.
