### ISSUE TITLE
Need tuning for Mongo WiredTiger Cache size

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-support#49]
Otherwise, Mongo goes on to consume - 50% of ($RAM - 1 GB)
Ref: https://access.redhat.com/solutions/4505561

**Comment by sthirugn** [comment]
This is currently being worked, I will post here when I have an update.

**Comment by pablomh** [comment]
Hi @sthirugn,

MongoDB hasn't been part of Satellite since 6.9 which is out of support. Do you think this issue could be closed?

**Comment by sthirugn** [comment]
ack @pabl
