### ISSUE TITLE
script to check pg_stat_activity queries running from postgres DB

### ISSUE THREAD

**Issue by snagoor** [RedHatSatellite/satellite-support#51]
It would be nice to have a script that reports the current queries that are triggered in PostgreSQL and how long they been running.

**Comment by sthirugn** [comment]
@snagoor I see https://github.com/RedHatSatellite/satellite-support/pull/52 is merged, but I see README is not updated. I propose to keep this issue open until README is updated.

**Comment by snagoor** [comment]
@sthirugn sure thing. Opened new PR to update README.md file https://github.com/RedHatSatellite/satellite-support/pull/55

**Comment by sthirugn** [comment]
PRs merged, closing this issue.
