### ISSUE TITLE
checkpoint_segments is no longer valid

### ISSUE THREAD

**Issue by matt8754** [RedHatSatellite/satellite-support#64]
Hitting below error when upgrading to 6.8:

Check if checkpoint_segments configuration exists on the system:      [FAIL]
ERROR: Tuning option 'checkpoint_segments' found.
This option is no longer valid for PostgreSQL 9.5 or newer.
Please remove it from following file and re-run the command.
- /etc/foreman-installer/custom-hiera.yaml

What is the equivalent option in  PostgreSQL 9.5?

**Comment by matt8754** [comment]
As per the doc:

**Comment by wbclark** [comment]
Hi @matt8754 , thanks for reaching out. It's interesting that the language you saw here seems to be somewhat different from the message that was inttroduced at https://github.com/theforeman/foreman-installer/pull/564 (see files changed --> `hooks/pre_validations/10-postgresql_checkpoint_segments.rb`)

I'm not very familiar with the `checkpoint_segments` parameter, but, the conversation on that PR seems to indicate that a suitable replacement should now be found in the tuning profiles? Have you been seeing related issues when using these?

**Comment by matt8754** [comment]
> Hi @matt8754 , thanks for reaching out. It's interesting that the language you saw here seems to be somewhat different from the message that was inttroduced at [theforeman/foreman-installer#564](https://github.com/theforeman/foreman-installer/pull/564) (see files changed --> `hooks/pre_validations/10-postgresql_checkpoint_segments.rb`)
> 
> I'm not very familiar with the `checkpoint_segments` parameter, but, the conversation on that PR seems to indicate that a suitable replacement should now be found in the tuning profiles? Have you been seeing related issues when using these?

Sorry for the late reply. Somehow I missed the notification. As we can see here, Satellite is not setting max_wal_size:

cat ./config/foreman.hiera/tuning/sizes/extra-extra-large.yaml
---
apache::mod::passenger::passenger_max_pool_size: 240
apache::mod::passenger::passenger_max_request_queue_size: 1000

apache::mod::prefork::serverlimit: 1024
apache::mod::prefork::maxclients: 1024
apache::mod::prefork::maxrequestsperchild: 4000

candlepin::java_opts: "-Xms1024m -Xmx8192m"

postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 32GB
  work_mem: 8MB
  effective_cache_size: 32GB
  autovacuum_vacuum_cost_limit: 2000 

I guess this should be fine as we can adjust it if needed in the future. I'm going to close this issue, thanks for looking at it.
